### ARAM Test
POST https://localhost:3000/api/dev
Content-Type: application/json

{
    "summonerName": "sirlunchalot619",
    "platformId": "EUW1",
    "matchId": 5123274952
}

### Summoner's Rift Test
POST https://localhost:3000/api/dev
Content-Type: application/json

{
    "summonerName": "scarfaZeGX",
    "platformId": "EUW1",
    "matchId": 5061906845
}

### Summoner's Rift Test
POST https://localhost:3000/api/dev
Content-Type: application/json

{
    "summonerName": "alice xP",
    "platformId": "EUN1",
    "matchId": 2687365610
}

### Trophy Stats
GET https://localhost:3000/api/trophy-stats/test

### Fix

GET https://localhost:3000/api/fix
